name: Pull Request

on:
  push:
    branches: [main]
    paths:
      - '**.go'
  pull_request:
    branches: [main]

jobs:
  generate:
    - uses: craicoverflow/openapi-generator-action@${GITHUB_REF##*/}
      with:
        generator: go
        input: ./examples/petstore-expanded.yaml