name: Pull Request

on:
  push:
    branches: [fix]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
      - uses: craicoverflow/openapi-generator-action@fix
        with:
          generator: go
          input: ./examples/petstore/petstore-expanded.yaml