name: Pull Request

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: craicoverflow/openapi-generator-action@fix
        with:
          generator: go
          input: ./examples/petstore-expanded.yaml